<?php
namespace App\Services\Warehouse\Logistics;
use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class WarehouseSalesLogisticsService {
 public function createDelivery(string $salesOrderId, object $user): object { return DB::transaction(function()use($salesOrderId,$user){
  $so=DB::table('wh_sales_orders')->lockForUpdate()->where('id',$salesOrderId)->whereNull('deleted_at')->first(); if(!$so) throw ValidationException::withMessages(['sales_order_id'=>'Sales Order tidak ditemukan.']); if(!in_array($so->status,['reserved','partially_reserved','ready'],true)) throw ValidationException::withMessages(['status'=>'Sales Order belum siap dibuatkan Delivery Order.']);
  $existing=DB::table('wh_sales_delivery_orders')->where('sales_order_id',$so->id)->first(); if($existing) return $existing;
  $id=(string)Str::ulid(); DB::table('wh_sales_delivery_orders')->insert(['id'=>$id,'delivery_number'=>$this->number('WH-DO'),'sales_order_id'=>$so->id,'warehouse_id'=>$so->warehouse_id,'customer_id'=>$so->customer_id,'ship_to_address_id'=>$so->ship_to_address_id,'delivery_type'=>$so->source_type==='chain_stock_request'?'sales_chain':'sales_external','status'=>'draft','idempotency_key'=>'sales-order:'.$so->id,'created_at'=>now(),'updated_at'=>now()]);
  $items=DB::table('wh_sales_order_items')->where('sales_order_id',$so->id)->get(); foreach($items as $item){$planned=min((float)$item->ordered_qty_base,(float)$item->reserved_qty_base ?: (float)$item->ordered_qty_base); DB::table('wh_sales_delivery_order_items')->insert(['id'=>(string)Str::ulid(),'delivery_order_id'=>$id,'sales_order_item_id'=>$item->id,'sku_id'=>$item->sku_id,'planned_qty_base'=>$planned,'unit_price_snapshot'=>$item->unit_price,'created_at'=>now(),'updated_at'=>now()]);}
  $this->event('delivery_order',$id,'created',['sales_order_id'=>$so->id],$user->id); return DB::table('wh_sales_delivery_orders')->where('id',$id)->first(); }); }
 public function dispatch(string $id,array $data,object $user):object{return DB::transaction(function()use($id,$data,$user){$do=DB::table('wh_sales_delivery_orders')->lockForUpdate()->where('id',$id)->first(); if(!$do||!in_array($do->status,['draft','ready'],true)) throw ValidationException::withMessages(['status'=>'Delivery Order tidak dapat dispatch.']); $items=DB::table('wh_sales_delivery_order_items')->where('delivery_order_id',$id)->get(); foreach($items as $item){DB::table('wh_sales_delivery_order_items')->where('id',$item->id)->update(['dispatched_qty_base'=>$item->planned_qty_base,'updated_at'=>now()]);}
  DB::table('wh_sales_delivery_orders')->where('id',$id)->update(['status'=>'dispatched','delivery_date'=>$data['delivery_date']??now()->toDateString(),'vehicle_number'=>$data['vehicle_number']??null,'driver_name'=>$data['driver_name']??null,'notes'=>$data['notes']??null,'dispatched_at'=>now(),'dispatched_by_user_id'=>$user->id,'updated_at'=>now()]); DB::table('wh_sales_orders')->where('id',$do->sales_order_id)->update(['status'=>'ready','updated_at'=>now()]); $this->event('delivery_order',$id,'dispatched',$data,$user->id); return DB::table('wh_sales_delivery_orders')->where('id',$id)->first();});}
 public function createReceipt(string $deliveryId,object $user):object{return DB::transaction(function()use($deliveryId,$user){$do=DB::table('wh_sales_delivery_orders')->where('id',$deliveryId)->first(); if(!$do||$do->status!=='dispatched') throw ValidationException::withMessages(['status'=>'DO belum dispatch.']); $old=DB::table('wh_sales_goods_receipts')->where('delivery_order_id',$deliveryId)->first(); if($old)return $old; $id=(string)Str::ulid(); DB::table('wh_sales_goods_receipts')->insert(['id'=>$id,'receipt_number'=>$this->number('WH-GR'),'delivery_order_id'=>$do->id,'sales_order_id'=>$do->sales_order_id,'warehouse_id'=>$do->warehouse_id,'customer_id'=>$do->customer_id,'status'=>'draft','receipt_date'=>now()->toDateString(),'idempotency_key'=>'delivery:'.$do->id,'created_at'=>now(),'updated_at'=>now()]); foreach(DB::table('wh_sales_delivery_order_items')->where('delivery_order_id',$do->id)->get() as $x) DB::table('wh_sales_goods_receipt_items')->insert(['id'=>(string)Str::ulid(),'goods_receipt_id'=>$id,'delivery_order_item_id'=>$x->id,'sku_id'=>$x->sku_id,'expected_qty_base'=>$x->dispatched_qty_base,'created_at'=>now(),'updated_at'=>now()]); $this->event('goods_receipt',$id,'created',[],$user->id); return DB::table('wh_sales_goods_receipts')->where('id',$id)->first();});}
 public function completeReceipt(string $id,array $items,?string $notes,object $user):object{return DB::transaction(function()use($id,$items,$notes,$user){$gr=DB::table('wh_sales_goods_receipts')->lockForUpdate()->where('id',$id)->first(); if(!$gr||!in_array($gr->status,['draft','submitted'],true)) throw ValidationException::withMessages(['status'=>'GR tidak dapat diselesaikan.']); $byId=collect($items)->keyBy('item_id'); $hasDiff=false; foreach(DB::table('wh_sales_goods_receipt_items')->where('goods_receipt_id',$id)->get() as $row){$input=$byId->get($row->id,[]);$received=(float)($input['received_qty_base']??$row->expected_qty_base);$damaged=(float)($input['damaged_qty_base']??0);$returned=(float)($input['returned_qty_base']??0); if($received<0||$damaged<0||$returned<0||$received+$damaged+$returned>(float)$row->expected_qty_base) throw ValidationException::withMessages(['items'=>'Quantity penerimaan tidak valid.']); $short=max(0,(float)$row->expected_qty_base-$received-$damaged-$returned);$hasDiff=$hasDiff||$short>0||$damaged>0||$returned>0; DB::table('wh_sales_goods_receipt_items')->where('id',$row->id)->update(['received_qty_base'=>$received,'short_qty_base'=>$short,'damaged_qty_base'=>$damaged,'returned_qty_base'=>$returned,'discrepancy_reason'=>$input['discrepancy_reason']??null,'updated_at'=>now()]); DB::table('wh_sales_delivery_order_items')->where('id',$row->delivery_order_item_id)->update(['received_qty_base'=>$received,'returned_qty_base'=>$returned,'updated_at'=>now()]); }
  DB::table('wh_sales_goods_receipts')->where('id',$id)->update(['status'=>'completed','completed_at'=>now(),'completed_by_user_id'=>$user->id,'notes'=>$notes,'updated_at'=>now()]); DB::table('wh_sales_delivery_orders')->where('id',$gr->delivery_order_id)->update(['status'=>'received','updated_at'=>now()]); DB::table('wh_sales_orders')->where('id',$gr->sales_order_id)->update(['status'=>'completed','updated_at'=>now()]); DB::table('wh_sales_order_reservations')->where('sales_order_id',$gr->sales_order_id)->where('status','active')->update(['status'=>'consumed','updated_at'=>now()]); $this->event('goods_receipt',$id,'completed',['has_discrepancy'=>$hasDiff],$user->id); return DB::table('wh_sales_goods_receipts')->where('id',$id)->first();});}
 public function createReturn(string $grId,array $data,object $user):object{return DB::transaction(function()use($grId,$data,$user){$gr=DB::table('wh_sales_goods_receipts')->where('id',$grId)->where('status','completed')->first();if(!$gr)throw ValidationException::withMessages(['goods_receipt_id'=>'GR completed tidak ditemukan.']);$id=(string)Str::ulid();DB::table('wh_sales_returns')->insert(['id'=>$id,'return_number'=>$this->number('WH-RET'),'goods_receipt_id'=>$gr->id,'sales_order_id'=>$gr->sales_order_id,'warehouse_id'=>$gr->warehouse_id,'customer_id'=>$gr->customer_id,'status'=>'submitted','return_date'=>$data['return_date']??now()->toDateString(),'reason'=>$data['reason'],'created_at'=>now(),'updated_at'=>now()]);foreach($data['items'] as $x)DB::table('wh_sales_return_items')->insert(['id'=>(string)Str::ulid(),'return_id'=>$id,'sku_id'=>$x['sku_id'],'qty_base'=>$x['qty_base'],'disposition'=>$x['disposition']??'quarantine','notes'=>$x['notes']??null,'created_at'=>now(),'updated_at'=>now()]);$this->event('return',$id,'submitted',[],$user->id);return DB::table('wh_sales_returns')->where('id',$id)->first();});}
 private function number(string $prefix):string{return $prefix.'-'.now()->format('Ymd').'-'.strtoupper(Str::random(6));} private function event(string $type,string $id,string $event,array $payload,?string $actor):void{DB::table('wh_logistics_events')->insert(['id'=>(string)Str::ulid(),'document_type'=>$type,'document_id'=>$id,'event_type'=>$event,'payload'=>json_encode($payload),'actor_user_id'=>$actor,'created_at'=>now(),'updated_at'=>now()]);}
}
