<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Sales;
use App\Http\Controllers\Controller; use App\Models\Warehouse\WarehouseSalesOrder; use App\Services\Warehouse\Sales\WarehouseSalesOrderService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class WarehouseSalesOrderController extends Controller {
 public function __construct(private WarehouseSalesOrderService $service){}
 public function index(Request $r):JsonResponse{$wid=$r->attributes->get('warehouse_scope_id');$q=WarehouseSalesOrder::query()->with(['customer','items.sku'])->when($wid,fn($x)=>$x->where('warehouse_id',$wid))->when($r->filled('status'),fn($x)=>$x->where('status',$r->string('status')))->when($r->filled('search'),fn($x)=>$x->where(fn($z)=>$z->where('order_number','like','%'.$r->string('search').'%')->orWhere('source_number','like','%'.$r->string('search').'%')))->latest('order_date')->latest('created_at');return response()->json(['success'=>true,'data'=>$q->paginate(min(100,max(10,$r->integer('per_page',25))))]);}
 public function options(Request $r):JsonResponse{$wid=$r->attributes->get('warehouse_scope_id');return response()->json(['success'=>true,'data'=>['warehouse_id'=>$wid,'customers'=>DB::table('wh_customers')->where('is_active',1)->whereNull('deleted_at')->orderBy('name')->get(['id','code','name','customer_type','price_tier_id']),'addresses'=>DB::table('wh_customer_addresses')->where('is_active',1)->whereNull('deleted_at')->get(['id','customer_id','label','address','is_default']),'skus'=>DB::table('stk_skus')->where('is_active',1)->whereNull('deleted_at')->orderBy('name')->get(['id','sku_code','name','base_uom_id','price_min','price_max']),'uoms'=>DB::table('stk_uoms')->where('is_active',1)->orderBy('name')->get(['id','code','name'])]]);}
 public function store(Request $r):JsonResponse{$data=$r->validate($this->rules());$data['warehouse_id']=$r->attributes->get('warehouse_scope_id')?:$data['warehouse_id'];return response()->json(['success'=>true,'data'=>$this->service->create($data,$r->user())],201);}
 public function update(Request $r,string $id):JsonResponse{$o=$this->find($r,$id);return response()->json(['success'=>true,'data'=>$this->service->update($o,$r->validate($this->rules(false)),$r->user())]);}
 public function submit(Request $r,string $id):JsonResponse{return response()->json(['success'=>true,'data'=>$this->service->submit($this->find($r,$id),$r->user())]);}
 public function approve(Request $r,string $id):JsonResponse{return response()->json(['success'=>true,'data'=>$this->service->approve($this->find($r,$id),$r->user())]);}
 public function requestCancel(Request $r,string $id):JsonResponse{$v=$r->validate(['reason'=>'required|string|max:1000']);return response()->json(['success'=>true,'data'=>$this->service->requestCancel($this->find($r,$id),$v['reason'],$r->user())]);}
 public function cancel(Request $r,string $id):JsonResponse{$v=$r->validate(['reason'=>'required|string|max:1000']);return response()->json(['success'=>true,'data'=>$this->service->cancel($this->find($r,$id),$v['reason'],$r->user())]);}
 public function import(Request $r):JsonResponse{$r->validate(['file'=>'required|file|mimes:csv,txt|max:5120']);$fh=fopen($r->file('file')->getRealPath(),'r');$header=array_map(fn($v)=>strtolower(trim((string)$v)),fgetcsv($fh)?:[]);$rows=[];while(($row=fgetcsv($fh))!==false)$rows[]=$row;fclose($fh);return response()->json(['success'=>true,'data'=>$this->service->importRows($rows,$header,$r->user(),(string)$r->attributes->get('warehouse_scope_id'))]);}
 public function template(){return response("external_order_number,order_date,customer_code,sku_code,quantity,conversion_factor,unit_price,discount_percent,tax_percent\nEXT-001,".now()->toDateString().",CUST-001,SKU-001,12,1,10000,0,0\n",200,['Content-Type'=>'text/csv','Content-Disposition'=>'attachment; filename="warehouse_sales_order_template.csv"']);}
 private function find(Request $r,string $id):WarehouseSalesOrder{$q=WarehouseSalesOrder::whereKey($id);if($wid=$r->attributes->get('warehouse_scope_id'))$q->where('warehouse_id',$wid);return $q->firstOrFail();}
 private function rules(bool $create=true):array{return ['warehouse_id'=>[$create?'nullable':'sometimes','string'],'customer_id'=>[$create?'required':'sometimes','string'],'ship_to_address_id'=>'nullable|string','source_type'=>'nullable|in:chain_stock_request,external_manual,external_upload','source_id'=>'nullable|string','source_number'=>'nullable|string|max:100','order_date'=>'nullable|date','requested_delivery_date'=>'nullable|date','notes'=>'nullable|string|max:3000','items'=>[$create?'required':'sometimes','array','min:1'],'items.*.sku_id'=>'required|string','items.*.uom_id'=>'nullable|string','items.*.ordered_qty'=>'required|numeric|gt:0','items.*.conversion_factor'=>'nullable|numeric|gt:0','items.*.unit_price'=>'required|numeric|min:0','items.*.discount_percent'=>'nullable|numeric|min:0|max:100','items.*.tax_percent'=>'nullable|numeric|min:0|max:100','items.*.notes'=>'nullable|string|max:500'];}
}
