<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Hardening;
use App\Http\Controllers\Controller;use App\Services\Warehouse\Hardening\WarehouseGoLiveGateService;use Illuminate\Http\JsonResponse;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Str;
class WarehouseHardeningController extends Controller{
 public function __construct(private WarehouseGoLiveGateService $service){}
 public function dashboard():JsonResponse{return response()->json(['data'=>$this->service->dashboard()]);}
 public function runs():JsonResponse{return response()->json(['data'=>DB::table('wh_go_live_runs')->latest('created_at')->paginate(20)]);}
 public function show(string $id):JsonResponse{return response()->json(['data'=>$this->service->runDetail($id)]);}
 public function run(Request $r):JsonResponse{$v=$r->validate(['environment'=>'nullable|string|max:40']);return response()->json(['data'=>$this->service->run((string)$r->user()?->id,$v['environment']??app()->environment())],201);}
 public function waive(Request $r,string $id):JsonResponse{$v=$r->validate(['reason'=>'required|string|min:20|max:2000']);return response()->json(['data'=>$this->service->waive($id,$v['reason'],(string)$r->user()?->id)]);}
 public function reversals(Request $r):JsonResponse{$q=DB::table('wh_reversal_requests')->latest('created_at');if($r->filled('status'))$q->where('status',$r->string('status'));return response()->json(['data'=>$q->paginate(25)]);}
 public function createReversal(Request $r):JsonResponse{$v=$r->validate(['document_type'=>'required|string|max:80','document_id'=>'required|string|max:40','document_number'=>'nullable|string|max:100','reason'=>'required|string|min:10|max:2000']);$id=(string)Str::ulid();DB::table('wh_reversal_requests')->insert(['id'=>$id,'request_number'=>'WH-REV-'.now()->format('Ymd').'-'.strtoupper(Str::random(6)),'document_type'=>$v['document_type'],'document_id'=>$v['document_id'],'document_number'=>$v['document_number']??null,'status'=>'submitted','reason'=>$v['reason'],'requested_by_user_id'=>(string)$r->user()?->id,'requested_at'=>now(),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['data'=>DB::table('wh_reversal_requests')->where('id',$id)->first()],201);}
 public function approveReversal(Request $r,string $id):JsonResponse{$v=$r->validate(['decision'=>'required|in:approve,reject','notes'=>'nullable|string|max:2000']);DB::transaction(function()use($r,$id,$v){$row=DB::table('wh_reversal_requests')->lockForUpdate()->where('id',$id)->first();abort_unless($row,404);abort_unless($row->status==='submitted',422,'Reversal sudah diproses.');DB::table('wh_reversal_requests')->where('id',$id)->update(['status'=>$v['decision']==='approve'?'approved':'rejected','approved_by_user_id'=>(string)$r->user()?->id,'approved_at'=>now(),'approval_notes'=>$v['notes']??null,'updated_at'=>now()]);});return response()->json(['data'=>DB::table('wh_reversal_requests')->where('id',$id)->first()]);}
}
