<?php

return [
    'modules' => [
        [
            'key' => 'dashboard',
            'code' => 'purchasing-dashboard',
            'label' => 'Dashboard',
            'singular_label' => 'Dashboard Purchasing',
            'description' => 'Ringkasan status pengembangan dan akses seluruh menu Purchasing.',
            'path' => '/portal/purchasing/dashboard',
            'route_name' => 'purchasing-dashboard',
            'sort_order' => 10,
            'permission' => 'purchasing.dashboard',
            'document_prefix' => 'PUR',
            'is_dashboard' => true,
        ],
        [
            'key' => 'fund-requests',
            'code' => 'purchasing-fund-requests',
            'label' => 'Fund Requests',
            'singular_label' => 'Fund Request',
            'description' => 'Fund Request untuk kebutuhan Purchase, Service, Reimburse, Asset, dan Stock.',
            'path' => '/purchasing/fund-requests',
            'route_name' => 'purchasing-fund-requests',
            'sort_order' => 20,
            'permission' => 'purchasing.fund_request',
            'document_prefix' => 'REQ',
        ],
        [
            'key' => 'order-management',
            'code' => 'purchasing-order-management',
            'label' => 'Order Management',
            'singular_label' => 'Order',
            'description' => 'Purchase, Service, Reimburse, Aktiva, dan Stock Order dalam satu workspace bertab.',
            'path' => '/purchasing/order-management',
            'route_name' => 'purchasing-order-management',
            'sort_order' => 30,
            'permission' => 'purchasing.order_management',
            'document_prefix' => 'ORD',
        ],
        [
            'key' => 'realization-orders',
            'code' => 'purchasing-realization-orders',
            'label' => 'Realization Order',
            'singular_label' => 'Realization',
            'description' => 'Service Entry Sheet, Service Acceptance, Reimburse Receipt, dan Goods Receipt dalam satu workspace realisasi.',
            'path' => '/purchasing/realization-orders',
            'route_name' => 'purchasing-realization-orders',
            'sort_order' => 40,
            'permission' => 'purchasing.realization_order',
            'document_prefix' => 'REAL',
        ],
        [
            'key' => 'account-payables',
            'code' => 'purchasing-account-payables',
            'label' => 'Account Payable',
            'singular_label' => 'Account Payable',
            'description' => 'Vendor Data, Incoming Invoice, AP Payment, dan AP Aging Report dalam satu workspace.',
            'path' => '/purchasing/account-payables',
            'route_name' => 'purchasing-account-payables',
            'sort_order' => 50,
            'permission' => 'purchasing.account_payable',
            'document_prefix' => 'AP',
        ],
        [
            'key' => 'account-receivables',
            'code' => 'purchasing-account-receivables',
            'label' => 'Account Receivable',
            'singular_label' => 'Account Receivable',
            'description' => 'Outgoing Invoice, AR Receipt, dan AR Aging Report dalam satu workspace.',
            'path' => '/purchasing/account-receivables',
            'route_name' => 'purchasing-account-receivables',
            'sort_order' => 60,
            'permission' => 'purchasing.account_receivable',
            'document_prefix' => 'AR',
        ],
    ],
];
