<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Finance;
use App\Http\Controllers\Controller; use App\Services\Warehouse\Finance\WarehouseFinanceService; use App\Services\Warehouse\Logistics\WarehouseSalesLogisticsService; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class WarehouseFinanceController extends Controller{public function __construct(private WarehouseFinanceService $service,private WarehouseSalesLogisticsService $logistics){}
 private function ids(Request $r):array{return collect($r->attributes->get('warehouse_scope_ids',[$r->attributes->get('warehouse_id')]))->filter()->values()->all();}
 public function dashboard(Request $r){return response()->json(['data'=>$this->service->dashboard($this->ids($r))]);}
 public function invoices(Request $r){$q=DB::table('wh_sales_invoices as i')->leftJoin('wh_customers as c','c.id','=','i.customer_id')->whereIn('i.warehouse_id',$this->ids($r))->select('i.*','c.customer_code','c.name as customer_name')->orderByDesc('i.invoice_date');if($r->filled('status'))$q->where('i.status',$r->status);if($r->filled('search'))$q->where(function($x)use($r){$x->where('i.invoice_number','like','%'.$r->search.'%')->orWhere('c.name','like','%'.$r->search.'%');});return response()->json($q->paginate(min((int)$r->input('per_page',25),100)));}
 public function generate(Request $r,string $grId){return response()->json(['data'=>$this->service->generateInvoice($grId,$r->user())],201);}
 public function completeReceiptAndInvoice(Request $r,string $id){$d=$r->validate(['items'=>'required|array','items.*.item_id'=>'required|string','items.*.received_qty_base'=>'nullable|numeric|min:0','items.*.damaged_qty_base'=>'nullable|numeric|min:0','items.*.returned_qty_base'=>'nullable|numeric|min:0','items.*.discrepancy_reason'=>'nullable|string|max:1000','notes'=>'nullable|string|max:2000']);$gr=$this->logistics->completeReceipt($id,$d['items'],$d['notes']??null,$r->user());$invoice=$this->service->generateInvoice($gr->id,$r->user());return response()->json(['data'=>['goods_receipt'=>$gr,'sales_invoice'=>$invoice]]);}
 public function receipts(Request $r){return response()->json(DB::table('wh_customer_receipts as p')->leftJoin('wh_customers as c','c.id','=','p.customer_id')->whereIn('p.warehouse_id',$this->ids($r))->select('p.*','c.name as customer_name')->orderByDesc('p.receipt_date')->paginate(min((int)$r->input('per_page',25),100)));}
 public function postReceipt(Request $r){$d=$r->validate(['sales_invoice_id'=>'required|string','receipt_date'=>'nullable|date','payment_method'=>'required|string|max:40','reference_number'=>'nullable|string|max:120','amount'=>'required|numeric|min:0.0001','idempotency_key'=>'nullable|string|max:140','notes'=>'nullable|string|max:2000']);return response()->json(['data'=>$this->service->postReceipt($d,$r->user())],201);}
 public function voidReceipt(Request $r,string $id){$d=$r->validate(['reason'=>'required|string|max:1000']);return response()->json(['data'=>$this->service->voidReceipt($id,$d['reason'],$r->user())]);}
 public function margin(Request $r){$rows=DB::table('wh_sales_invoice_items as x')->join('wh_sales_invoices as i','i.id','=','x.sales_invoice_id')->leftJoin('stk_skus as s','s.id','=','x.sku_id')->whereIn('i.warehouse_id',$this->ids($r))->where('i.status','!=','void')->groupBy('x.sku_id','s.code','s.name')->selectRaw('x.sku_id,s.code as sku_code,s.name as sku_name,SUM(x.quantity_base) quantity_base,SUM(x.line_total) revenue,SUM(x.cogs_total) cogs,SUM(x.gross_margin) gross_margin')->orderByDesc('gross_margin')->paginate(min((int)$r->input('per_page',50),100));return response()->json($rows);}
}