<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration{public function up():void{
 if(!Schema::hasTable('wh_supplier_invoices'))Schema::create('wh_supplier_invoices',function(Blueprint $t){$t->ulid('id')->primary();$t->string('invoice_number',70)->unique();$t->foreignUlid('purchase_order_id')->unique();$t->foreignUlid('stock_in_id')->unique();$t->foreignUlid('warehouse_id');$t->foreignUlid('supplier_source_id');$t->date('invoice_date');$t->date('due_date')->nullable();$t->string('currency_code',3)->default('IDR');$t->decimal('subtotal',22,2)->default(0);$t->decimal('discount_total',22,2)->default(0);$t->decimal('tax_total',22,2)->default(0);$t->decimal('landed_cost_total',22,2)->default(0);$t->decimal('grand_total',22,2)->default(0);$t->decimal('paid_total',22,2)->default(0);$t->decimal('balance_due',22,2)->default(0);$t->string('status',24)->default('issued')->index();$t->string('idempotency_key',180)->unique();$t->foreignUlid('issued_by_user_id')->nullable();$t->timestamp('issued_at')->nullable();$t->timestamps();$t->index(['warehouse_id','status','due_date'],'wh_sinv_wh_status_due_idx');});
 if(!Schema::hasTable('wh_supplier_invoice_items'))Schema::create('wh_supplier_invoice_items',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('supplier_invoice_id');$t->foreignUlid('purchase_order_item_id');$t->foreignUlid('stock_in_item_id');$t->foreignUlid('sku_id');$t->decimal('quantity_base',18,4);$t->decimal('unit_price',20,6)->default(0);$t->decimal('line_subtotal',22,2)->default(0);$t->decimal('discount_amount',22,2)->default(0);$t->decimal('tax_amount',22,2)->default(0);$t->decimal('landed_cost_allocated',22,2)->default(0);$t->decimal('inventory_cost_total',22,2)->default(0);$t->decimal('effective_unit_cost',20,6)->default(0);$t->json('source_snapshot')->nullable();$t->timestamps();$t->unique(['supplier_invoice_id','stock_in_item_id'],'wh_sinv_item_stockin_uq');});
 if(!Schema::hasTable('wh_landed_costs'))Schema::create('wh_landed_costs',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('supplier_invoice_id');$t->string('cost_type',40);$t->string('description',255)->nullable();$t->decimal('amount',22,2);$t->string('allocation_method',24)->default('value');$t->foreignUlid('created_by_user_id')->nullable();$t->timestamps();$t->index(['supplier_invoice_id','cost_type'],'wh_landed_invoice_type_idx');});
 if(!Schema::hasTable('wh_supplier_payments'))Schema::create('wh_supplier_payments',function(Blueprint $t){$t->ulid('id')->primary();$t->string('payment_number',70)->unique();$t->foreignUlid('warehouse_id');$t->foreignUlid('supplier_source_id');$t->date('payment_date');$t->string('payment_method',30);$t->string('reference_number',120)->nullable();$t->decimal('amount',22,2);$t->string('status',20)->default('posted')->index();$t->string('idempotency_key',180)->unique();$t->text('notes')->nullable();$t->foreignUlid('posted_by_user_id')->nullable();$t->timestamp('posted_at')->nullable();$t->timestamps();});
 if(!Schema::hasTable('wh_supplier_payment_allocations'))Schema::create('wh_supplier_payment_allocations',function(Blueprint $t){$t->ulid('id')->primary();$t->foreignUlid('supplier_payment_id');$t->foreignUlid('supplier_invoice_id');$t->decimal('allocated_amount',22,2);$t->timestamps();$t->unique(['supplier_payment_id','supplier_invoice_id'],'wh_spay_invoice_uq');});
 if(!Schema::hasTable('wh_purchasing_events'))Schema::create('wh_purchasing_events',function(Blueprint $t){$t->ulid('id')->primary();$t->string('document_type',40);$t->ulid('document_id');$t->string('event_type',60);$t->json('payload')->nullable();$t->foreignUlid('actor_user_id')->nullable();$t->timestamps();$t->index(['document_type','document_id','created_at'],'wh_pevent_doc_idx');});
 }public function down():void{/* non-destructive */}};
