<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
return new class extends Migration {
 public function up():void {
  foreach(['finance_settlement_sources','finance_journal_entries','finance_chart_of_accounts'] as $x)if(!Schema::hasTable($x))throw new RuntimeException("HOTFIX 03 membutuhkan {$x}.");
  if(!Schema::hasTable('finance_settlement_batches'))Schema::create('finance_settlement_batches',function(Blueprint $t):void{$t->ulid('id')->primary();$t->string('batch_key',64)->unique();$t->string('batch_no',64)->unique();$t->date('settlement_date')->index();$t->string('company_code',16)->index();$t->char('outlet_id',26)->index();$t->string('payment_label',255);$t->char('bank_account_id',26)->index();$t->char('mdr_expense_account_id',26)->nullable()->index();$t->char('admin_fee_expense_account_id',26)->nullable()->index();$t->decimal('clearing_amount',18,2);$t->decimal('bank_received_amount',18,2);$t->decimal('mdr_amount',18,2);$t->decimal('admin_fee_amount',18,2);$t->string('status',16)->default('DRAFT')->index();$t->unsignedInteger('posting_version')->default(0);$t->timestamp('posted_at')->nullable();$t->char('posted_by_user_id',26)->nullable();$t->timestamp('reopened_at')->nullable();$t->char('reopened_by_user_id',26)->nullable();$t->text('reopen_reason')->nullable();$t->char('created_by_user_id',26)->nullable();$t->char('updated_by_user_id',26)->nullable();$t->timestamps();$t->index(['outlet_id','settlement_date','status'],'fin_hf3_stlb_out_date_idx');});
  if(!Schema::hasTable('finance_settlement_bulk_items'))Schema::create('finance_settlement_bulk_items',function(Blueprint $t):void{$t->ulid('id')->primary();$t->char('batch_id',26)->index('fin_hf3_stlbi_batch_idx');$t->char('settlement_source_id',26)->index('fin_hf3_stlbi_src_idx');$t->string('marking',16)->index('fin_hf3_stlbi_mark_idx');$t->string('payment_method_name',120);$t->char('clearing_account_id',26)->index('fin_hf3_stlbi_clear_idx');$t->decimal('clearing_amount',18,2);$t->timestamps();$t->foreign('batch_id','fin_hf3_stlbi_batch_fk')->references('id')->on('finance_settlement_batches')->cascadeOnDelete();$t->foreign('settlement_source_id','fin_hf3_stlbi_src_fk')->references('id')->on('finance_settlement_sources')->restrictOnDelete();$t->unique(['batch_id','settlement_source_id'],'fin_hf3_stlbi_batch_src_uq');});
  if(!Schema::hasTable('finance_settlement_bulk_journals'))Schema::create('finance_settlement_bulk_journals',function(Blueprint $t):void{$t->ulid('id')->primary();$t->char('batch_id',26)->index('fin_hf3_stlbj_batch_idx');$t->unsignedInteger('posting_version');$t->string('marking',16);$t->char('journal_entry_id',26)->index('fin_hf3_stlbj_j_idx');$t->string('journal_no',48);$t->char('reversal_journal_id',26)->nullable()->index('fin_hf3_stlbj_rev_idx');$t->string('reversal_journal_no',48)->nullable();$t->timestamp('posted_at');$t->timestamp('reversed_at')->nullable();$t->timestamps();$t->foreign('batch_id','fin_hf3_stlbj_batch_fk')->references('id')->on('finance_settlement_batches')->cascadeOnDelete();$t->foreign('journal_entry_id','fin_hf3_stlbj_j_fk')->references('id')->on('finance_journal_entries')->restrictOnDelete();$t->unique(['batch_id','posting_version','marking'],'fin_hf3_stlbj_ver_mark_uq');});
  Permission::findOrCreate('finance.reset.manage','web');Role::query()->where('guard_name','web')->whereIn(DB::raw('LOWER(name)'),['admin','administrator','superadmin','super-admin'])->get()->each(fn(Role $r)=>$r->givePermissionTo('finance.reset.manage'));
  if(Schema::hasTable('access_portals')&&Schema::hasTable('access_menus')){$portal=DB::table('access_portals')->where('code','finance')->first();if($portal){$old=DB::table('access_menus')->where('code','finance-reset')->first();$id=(string)($old->id??Str::ulid());DB::table('access_menus')->updateOrInsert(['code'=>'finance-reset'],['id'=>$id,'portal_id'=>$portal->id,'name'=>'Reset Reconciliation & Settlement','path'=>'/finance/reset','sort_order'=>125,'permission_view'=>'finance.reset.manage','permission_create'=>'finance.reset.manage','permission_update'=>'finance.reset.manage','permission_delete'=>'finance.reset.manage','is_active'=>true,'created_at'=>$old->created_at??now(),'updated_at'=>now()]);if(Schema::hasTable('access_role_menu_permissions')&&Schema::hasTable('access_roles')){foreach(DB::table('access_roles')->get(['id','code','spatie_role_name']) as $role){$admin=str_contains(strtoupper((string)$role->code),'ADMIN')||str_contains(strtolower((string)$role->spatie_role_name),'admin');if(!$admin)continue;$exists=DB::table('access_role_menu_permissions')->where('access_role_id',$role->id)->where('menu_id',$id)->whereNull('access_level_id')->exists();if(!$exists)DB::table('access_role_menu_permissions')->insert(['id'=>(string)Str::ulid(),'access_role_id'=>$role->id,'access_level_id'=>null,'menu_id'=>$id,'can_view'=>true,'can_create'=>true,'can_edit'=>true,'can_delete'=>true,'created_at'=>now(),'updated_at'=>now()]);}}}}
  if(Schema::hasTable('access_role_menu_permissions')&&Schema::hasTable('access_roles')&&Schema::hasTable('access_menus')){$resetId=DB::table('access_menus')->where('code','finance-reset')->value('id');$sourceId=DB::table('access_menus')->where('code','finance-dashboard')->value('id');if($resetId&&$sourceId){foreach(DB::table('access_role_menu_permissions as rp')->join('access_roles as ar','ar.id','=','rp.access_role_id')->where('rp.menu_id',$sourceId)->get(['rp.access_role_id','rp.access_level_id','ar.code','ar.spatie_role_name']) as $row){$admin=str_contains(strtoupper((string)$row->code),'ADMIN')||str_contains(strtolower((string)$row->spatie_role_name),'admin');if(!$admin)continue;$q=DB::table('access_role_menu_permissions')->where('access_role_id',$row->access_role_id)->where('menu_id',$resetId);$row->access_level_id===null?$q->whereNull('access_level_id'):$q->where('access_level_id',$row->access_level_id);if(!$q->exists())DB::table('access_role_menu_permissions')->insert(['id'=>(string)Str::ulid(),'access_role_id'=>$row->access_role_id,'access_level_id'=>$row->access_level_id,'menu_id'=>$resetId,'can_view'=>true,'can_create'=>true,'can_edit'=>true,'can_delete'=>true,'created_at'=>now(),'updated_at'=>now()]);}}}
  if(Schema::hasTable('sales')){try{Schema::table('sales',fn(Blueprint $t)=>$t->index(['outlet_id','status','created_at'],'fin_hf3_sales_out_status_date_idx'));}catch(Throwable){}}
  if(Schema::hasTable('sale_payments')){try{Schema::table('sale_payments',fn(Blueprint $t)=>$t->index(['sale_id','payment_method_id'],'fin_hf3_pay_sale_method_idx'));}catch(Throwable){}}
  if(Schema::hasTable('cogs_calculation_runs')){try{Schema::table('cogs_calculation_runs',fn(Blueprint $t)=>$t->index(['outlet_id','period_from','period_to','status'],'fin_hf3_cogs_out_period_status_idx'));}catch(Throwable){}}
 }
 public function down():void {if(Schema::hasTable('access_menus'))DB::table('access_menus')->where('code','finance-reset')->delete();Schema::dropIfExists('finance_settlement_bulk_journals');Schema::dropIfExists('finance_settlement_bulk_items');Schema::dropIfExists('finance_settlement_batches');}
};
