<?php
namespace App\Services\Warehouse\Sales;
use App\Models\Warehouse\WarehouseSalesOrder; use Illuminate\Support\Facades\DB; use Illuminate\Support\Str; use Illuminate\Validation\ValidationException;
class WarehouseSalesOrderService {
 public function create(array $data, object $user): WarehouseSalesOrder { return DB::transaction(function() use($data,$user){ $warehouseId=$data['warehouse_id']; $customer=DB::table('wh_customers')->where('id',$data['customer_id'])->whereNull('deleted_at')->first(); if(!$customer||!$customer->is_active) throw ValidationException::withMessages(['customer_id'=>'Customer tidak aktif atau tidak ditemukan.']); $order=WarehouseSalesOrder::create(['order_number'=>$this->number(),'warehouse_id'=>$warehouseId,'customer_id'=>$customer->id,'ship_to_address_id'=>$data['ship_to_address_id']??null,'source_type'=>$data['source_type']??'external_manual','source_id'=>$data['source_id']??null,'source_number'=>$data['source_number']??null,'order_date'=>$data['order_date']??now()->toDateString(),'requested_delivery_date'=>$data['requested_delivery_date']??null,'currency_code'=>'IDR','status'=>'draft','notes'=>$data['notes']??null,'created_by_user_id'=>$user->id,'updated_by_user_id'=>$user->id]); $this->replaceItems($order,$data['items']); $this->event($order,'created',null,'draft',['source_type'=>$order->source_type],$user->id); return $order->fresh(['items.sku','customer']); }); }
 public function update(WarehouseSalesOrder $order,array $data,object $user): WarehouseSalesOrder { if(!in_array($order->status,['draft','submitted'],true)) throw ValidationException::withMessages(['status'=>'Dokumen tidak dapat diubah pada status ini.']); return DB::transaction(function()use($order,$data,$user){$order->fill(array_filter(['customer_id'=>$data['customer_id']??null,'ship_to_address_id'=>$data['ship_to_address_id']??null,'requested_delivery_date'=>$data['requested_delivery_date']??null,'notes'=>$data['notes']??null],fn($v)=>$v!==null))->forceFill(['updated_by_user_id'=>$user->id])->save(); if(isset($data['items'])) $this->replaceItems($order,$data['items']); return $order->fresh(['items.sku','customer']);}); }
 public function submit(WarehouseSalesOrder $order,object $user): WarehouseSalesOrder { return $this->transition($order,['draft'],'submitted','submitted',$user); }
 public function approve(WarehouseSalesOrder $order,object $user): WarehouseSalesOrder { return DB::transaction(function()use($order,$user){$this->transition($order,['submitted'],'approved','approved',$user); $this->reserve($order,$user); return $order->fresh(['items.sku','customer']);}); }
 public function requestCancel(WarehouseSalesOrder $order,string $reason,object $user): WarehouseSalesOrder { if(!in_array($order->status,['submitted','approved','reserved','partially_reserved','ready'],true)) throw ValidationException::withMessages(['status'=>'Pembatalan tidak tersedia.']); $from=$order->status; $order->update(['status'=>'cancel_requested','cancellation_reason'=>$reason,'updated_by_user_id'=>$user->id]); $this->event($order,'cancel_requested',$from,'cancel_requested',['reason'=>$reason],$user->id); return $order; }
 public function cancel(WarehouseSalesOrder $order,string $reason,object $user): WarehouseSalesOrder { return DB::transaction(function()use($order,$reason,$user){if(!in_array($order->status,['draft','submitted','approved','reserved','partially_reserved','cancel_requested'],true)) throw ValidationException::withMessages(['status'=>'Dokumen tidak dapat dibatalkan.']); DB::table('wh_sales_order_reservations')->where('sales_order_id',$order->id)->where('status','active')->update(['status'=>'released','released_at'=>now(),'updated_at'=>now()]); $from=$order->status; $order->update(['status'=>'cancelled','cancellation_reason'=>$reason,'cancelled_by_user_id'=>$user->id,'cancelled_at'=>now(),'updated_by_user_id'=>$user->id]); $this->event($order,'cancelled',$from,'cancelled',['reason'=>$reason],$user->id); return $order;}); }
 public function importRows(array $rows,array $header,object $user,string $warehouseId): array { $created=[];$errors=[]; foreach($rows as $i=>$row){$r=array_combine($header,array_pad($row,count($header),null)); try{$customer=DB::table('wh_customers')->where('code',trim((string)($r['customer_code']??'')))->whereNull('deleted_at')->first(); $sku=DB::table('stk_skus')->where('sku_code',trim((string)($r['sku_code']??'')))->whereNull('deleted_at')->first(); if(!$customer||!$sku) throw new \RuntimeException('customer_code atau sku_code tidak ditemukan'); $key=$customer->id.'|'.($r['external_order_number']??''); $created[$key]??=['customer_id'=>$customer->id,'source_type'=>'external_upload','source_number'=>$r['external_order_number']??null,'order_date'=>$r['order_date']??now()->toDateString(),'notes'=>'Imported CSV','items'=>[]]; $created[$key]['items'][]=['sku_id'=>$sku->id,'ordered_qty'=>(float)($r['quantity']??0),'conversion_factor'=>(float)($r['conversion_factor']??1),'unit_price'=>(float)($r['unit_price']??0),'discount_percent'=>(float)($r['discount_percent']??0),'tax_percent'=>(float)($r['tax_percent']??0)];}catch(\Throwable $e){$errors[]=['row'=>$i+2,'message'=>$e->getMessage()];}} $ids=[]; foreach($created as $doc){$doc['warehouse_id']=$warehouseId;$ids[]=$this->create($doc,$user)->id;} return ['created'=>count($ids),'ids'=>$ids,'errors'=>$errors]; }
 private function replaceItems(WarehouseSalesOrder $order,array $items): void { DB::table('wh_sales_order_items')->where('sales_order_id',$order->id)->delete(); $sub=$disc=$tax=$grand=0; foreach($items as $x){$qty=(float)$x['ordered_qty'];$factor=(float)($x['conversion_factor']??1);$price=(float)($x['unit_price']??0);$dp=(float)($x['discount_percent']??0);$tp=(float)($x['tax_percent']??0); if($qty<=0||$factor<=0) throw ValidationException::withMessages(['items'=>'Quantity dan conversion factor harus lebih dari nol.']); $gross=$qty*$price;$d=$gross*$dp/100;$t=($gross-$d)*$tp/100;$line=$gross-$d+$t; DB::table('wh_sales_order_items')->insert(['id'=>(string)Str::ulid(),'sales_order_id'=>$order->id,'sku_id'=>$x['sku_id'],'uom_id'=>$x['uom_id']??null,'conversion_factor'=>$factor,'ordered_qty'=>$qty,'ordered_qty_base'=>$qty*$factor,'reserved_qty_base'=>0,'fulfilled_qty_base'=>0,'unit_price'=>$price,'discount_percent'=>$dp,'discount_amount'=>$d,'tax_percent'=>$tp,'tax_amount'=>$t,'line_total'=>$line,'price_source'=>$x['price_source']??'manual','price_snapshot'=>json_encode(['unit_price'=>$price,'discount_percent'=>$dp,'tax_percent'=>$tp]),'notes'=>$x['notes']??null,'created_at'=>now(),'updated_at'=>now()]);$sub+=$gross;$disc+=$d;$tax+=$t;$grand+=$line;} $order->update(['subtotal'=>$sub,'discount_total'=>$disc,'tax_total'=>$tax,'grand_total'=>$grand]); }
 private function reserve(WarehouseSalesOrder $order,object $user): void { $full=true;$any=false; foreach($order->items()->get() as $item){$available=(float)DB::table('wh_batch_balances')->where('warehouse_id',$order->warehouse_id)->where('sku_id',$item->sku_id)->sum('available_qty_base');$qty=min($available,(float)$item->ordered_qty_base); if($qty>0){DB::table('wh_sales_order_reservations')->insert(['id'=>(string)Str::ulid(),'sales_order_id'=>$order->id,'sales_order_item_id'=>$item->id,'warehouse_id'=>$order->warehouse_id,'sku_id'=>$item->sku_id,'reserved_qty_base'=>$qty,'status'=>'active','created_by_user_id'=>$user->id,'created_at'=>now(),'updated_at'=>now()]);$item->update(['reserved_qty_base'=>$qty]);$any=true;} if($qty<(float)$item->ordered_qty_base)$full=false;} $status=$full?'reserved':($any?'partially_reserved':'approved');$from=$order->status;$order->update(['status'=>$status]);$this->event($order,'reservation_completed',$from,$status,[],$user->id); }
 private function transition(WarehouseSalesOrder $order,array $allowed,string $to,string $event,object $user): WarehouseSalesOrder { if(!in_array($order->status,$allowed,true)) throw ValidationException::withMessages(['status'=>'Transisi status tidak valid.']); $from=$order->status;$payload=['status'=>$to,'updated_by_user_id'=>$user->id]; if($to==='submitted')$payload+=['submitted_by_user_id'=>$user->id,'submitted_at'=>now()]; if($to==='approved')$payload+=['approved_by_user_id'=>$user->id,'approved_at'=>now()];$order->update($payload);$this->event($order,$event,$from,$to,[],$user->id);return $order; }
 private function event($order,$event,$from,$to,$payload,$actor):void{DB::table('wh_sales_order_events')->insert(['id'=>(string)Str::ulid(),'sales_order_id'=>$order->id,'event_type'=>$event,'from_status'=>$from,'to_status'=>$to,'payload'=>json_encode($payload),'actor_user_id'=>$actor,'created_at'=>now(),'updated_at'=>now()]);}
 private function number():string{return 'WH-SO-'.now()->format('Ymd').'-'.strtoupper(Str::random(6));}
}
