<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Production;
use App\Http\Controllers\Controller;
use App\Services\Warehouse\Production\WarehouseProductionV2Service;
use Illuminate\Http\Request;
class WarehouseProductionV2Controller extends Controller {
 public function __construct(private WarehouseProductionV2Service $service){}
 private function wh(Request $r): string { return (string)($r->attributes->get('warehouse_id') ?: $r->user()?->warehouse_id ?: $r->query('warehouse_id')); }
 public function dashboard(Request $r){return response()->json(['data'=>$this->service->dashboard($this->wh($r),$r->only('from','to'))]);}
 public function boms(Request $r){return response()->json(['data'=>$this->service->listBoms($this->wh($r),$r->only('q'))]);}
 public function storeBom(Request $r){$p=$r->validate(['bom_code'=>'nullable|string|max:60','name'=>'required|string|max:160','scope'=>'nullable|in:warehouse,global','output_sku_id'=>'required|string','output_uom_id'=>'required|string','standard_output_qty'=>'required|numeric|min:0.0001','version'=>'nullable|integer|min:1','is_active'=>'nullable|boolean','effective_from'=>'nullable|date','effective_to'=>'nullable|date|after_or_equal:effective_from','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.input_sku_id'=>'required|string','items.*.input_uom_id'=>'required|string','items.*.qty_per_output'=>'required|numeric|min:0.0001','items.*.conversion_factor_snapshot'=>'nullable|numeric|min:0.00000001','items.*.expected_waste_percent'=>'nullable|numeric|min:0|max:100','items.*.is_optional'=>'nullable|boolean','items.*.notes'=>'nullable|string']);return response()->json(['data'=>$this->service->saveBom(null,$this->wh($r),$p,(string)$r->user()->id)],201);}
 public function updateBom(Request $r,string $id){$p=$r->validate(['bom_code'=>'nullable|string|max:60','name'=>'required|string|max:160','scope'=>'nullable|in:warehouse,global','output_sku_id'=>'required|string','output_uom_id'=>'required|string','standard_output_qty'=>'required|numeric|min:0.0001','version'=>'nullable|integer|min:1','is_active'=>'nullable|boolean','effective_from'=>'nullable|date','effective_to'=>'nullable|date|after_or_equal:effective_from','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.input_sku_id'=>'required|string','items.*.input_uom_id'=>'required|string','items.*.qty_per_output'=>'required|numeric|min:0.0001','items.*.expected_waste_percent'=>'nullable|numeric|min:0|max:100','items.*.is_optional'=>'nullable|boolean']);return response()->json(['data'=>$this->service->saveBom($id,$this->wh($r),$p,(string)$r->user()->id)]);}
 public function costing(Request $r,string $id){return response()->json(['data'=>$this->service->costing($id)]);}
 public function addCost(Request $r,string $id){$p=$r->validate(['component_type'=>'required|in:labor,overhead,utility,packaging,other','description'=>'required|string|max:180','amount'=>'required|numeric|min:0','allocation_method'=>'nullable|in:output_qty,equal,manual','metadata'=>'nullable|array']);return response()->json(['data'=>$this->service->recordCost($id,$this->wh($r),$p,(string)$r->user()->id)]);}
 public function addWaste(Request $r,string $id){$p=$r->validate(['sku_id'=>'nullable|string','waste_type'=>'required|in:process_loss,damage,expired,quality_reject,spillage,other','qty_base'=>'required|numeric|min:0.0001','unit_cost_snapshot'=>'nullable|numeric|min:0','disposition'=>'nullable|in:discard,rework,quarantine,return_supplier','reason'=>'required|string|max:1000']);return response()->json(['data'=>$this->service->recordWaste($id,$this->wh($r),$p,(string)$r->user()->id)]);}
 public function reconcile(Request $r,string $id){return response()->json(['data'=>$this->service->reconcile($id,$this->wh($r),(string)$r->user()->id)]);}
}
