<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Logistics;
use App\Http\Controllers\Controller; use App\Services\Warehouse\Logistics\WarehouseSalesLogisticsService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class WarehouseSalesLogisticsController extends Controller { public function __construct(private WarehouseSalesLogisticsService $service){}
 public function index(Request $r):JsonResponse{$warehouseId=$r->attributes->get('warehouse_id')??$r->user()?->warehouse_id; $q=DB::table('wh_sales_delivery_orders as d')->join('wh_sales_orders as so','so.id','=','d.sales_order_id')->join('wh_customers as c','c.id','=','d.customer_id')->select('d.*','so.order_number','c.code as customer_code','c.name as customer_name')->orderByDesc('d.created_at'); if($warehouseId)$q->where('d.warehouse_id',$warehouseId); if($r->filled('status'))$q->where('d.status',$r->status); return response()->json(['data'=>$q->paginate(25)]);}
 public function show(string $id):JsonResponse{$do=DB::table('wh_sales_delivery_orders')->where('id',$id)->firstOrFail();return response()->json(['data'=>['delivery'=>$do,'items'=>DB::table('wh_sales_delivery_order_items')->where('delivery_order_id',$id)->get(),'receipt'=>DB::table('wh_sales_goods_receipts')->where('delivery_order_id',$id)->first()]]);}
 public function createDelivery(Request $r):JsonResponse{$v=$r->validate(['sales_order_id'=>'required|string']);return response()->json(['data'=>$this->service->createDelivery($v['sales_order_id'],$r->user())],201);}
 public function dispatch(Request $r,string $id):JsonResponse{$v=$r->validate(['delivery_date'=>'nullable|date','vehicle_number'=>'nullable|string|max:50','driver_name'=>'nullable|string|max:100','notes'=>'nullable|string']);return response()->json(['data'=>$this->service->dispatch($id,$v,$r->user())]);}
 public function createReceipt(Request $r,string $id):JsonResponse{return response()->json(['data'=>$this->service->createReceipt($id,$r->user())],201);}
 public function completeReceipt(Request $r,string $id):JsonResponse{$v=$r->validate(['items'=>'required|array|min:1','items.*.item_id'=>'required|string','items.*.received_qty_base'=>'required|numeric|min:0','items.*.damaged_qty_base'=>'nullable|numeric|min:0','items.*.returned_qty_base'=>'nullable|numeric|min:0','items.*.discrepancy_reason'=>'nullable|string|max:160','notes'=>'nullable|string']);return response()->json(['data'=>$this->service->completeReceipt($id,$v['items'],$v['notes']??null,$r->user())]);}
 public function returns(Request $r):JsonResponse{return response()->json(['data'=>DB::table('wh_sales_returns')->orderByDesc('created_at')->paginate(25)]);} public function createReturn(Request $r,string $grId):JsonResponse{$v=$r->validate(['return_date'=>'nullable|date','reason'=>'required|string','items'=>'required|array|min:1','items.*.sku_id'=>'required|string','items.*.qty_base'=>'required|numeric|gt:0','items.*.disposition'=>'nullable|in:restock,quarantine,damaged','items.*.notes'=>'nullable|string']);return response()->json(['data'=>$this->service->createReturn($grId,$v,$r->user())],201);}
}
