<?php
namespace App\Http\Controllers\Api\V1\Warehouse\Purchasing;
use App\Http\Controllers\Controller; use App\Http\Controllers\Api\V1\Warehouse\Procurement\WarehouseStockInController; use App\Services\Warehouse\Purchasing\WarehousePurchasingFinanceService; use Illuminate\Http\JsonResponse; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class WarehousePurchasingFinanceController extends Controller{public function __construct(private WarehousePurchasingFinanceService $service){}
 private function ids(Request $r):array{return array_values(array_filter((array)($r->attributes->get('warehouse_ids')??[$r->attributes->get('warehouse_id')])));}
 public function dashboard(Request $r):JsonResponse{return response()->json(['data'=>$this->service->dashboard($this->ids($r))]);}
 public function invoices(Request $r):JsonResponse{$q=DB::table('wh_supplier_invoices as i')->leftJoin('pur_supplier_sources as s','s.id','=','i.supplier_source_id')->whereIn('i.warehouse_id',$this->ids($r))->select('i.*','s.name as supplier_name')->orderByDesc('i.invoice_date');return response()->json(['data'=>$q->paginate(min((int)$r->input('per_page',25),100))]);}
 public function payments(Request $r):JsonResponse{return response()->json(['data'=>DB::table('wh_supplier_payments')->whereIn('warehouse_id',$this->ids($r))->orderByDesc('payment_date')->paginate(min((int)$r->input('per_page',25),100))]);}
 public function approveStockIn(Request $r,string $id,WarehouseStockInController $original):JsonResponse{$response=$original->approve($r,$id);if($response->getStatusCode()>=400)return $response;$invoice=$this->service->generateInvoice($id,$r->user());$payload=$response->getData(true);$payload['data']['supplier_invoice']=$invoice;return response()->json($payload,$response->getStatusCode());}
 public function generate(Request $r,string $stockInId):JsonResponse{return response()->json(['data'=>$this->service->generateInvoice($stockInId,$r->user())]);}
 public function landed(Request $r,string $id):JsonResponse{$d=$r->validate(['cost_type'=>'required|string|max:40','description'=>'nullable|string|max:255','amount'=>'required|numeric|min:0.01','allocation_method'=>'required|in:value,quantity']);return response()->json(['data'=>$this->service->allocateLandedCost($id,$d,$r->user())]);}
 public function pay(Request $r):JsonResponse{$d=$r->validate(['supplier_invoice_id'=>'required|string','payment_date'=>'nullable|date','payment_method'=>'required|in:transfer,cash,qris,other','reference_number'=>'nullable|string|max:120','amount'=>'required|numeric|min:0.01','idempotency_key'=>'nullable|string|max:180','notes'=>'nullable|string']);return response()->json(['data'=>$this->service->postPayment($d,$r->user())]);}
 public function voidPayment(Request $r,string $id):JsonResponse{$d=$r->validate(['reason'=>'required|string|max:500']);return response()->json(['data'=>$this->service->voidPayment($id,$d['reason'],$r->user())]);}}
